// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActiveConnection struct {
	DisplayName   string             `json:"display_name"`
	LastSeen      pgtype.Timestamptz `json:"last_seen"`
	Status        string             `json:"status"`
	CurrentRoomID pgtype.UUID        `json:"current_room_id"`
}

type Player struct {
	ID                pgtype.UUID        `json:"id"`
	RoomID            pgtype.UUID        `json:"room_id"`
	PlayerDisplayName string             `json:"player_display_name"`
	PlayerOrder       int16              `json:"player_order"`
	JoinedAt          pgtype.Timestamptz `json:"joined_at"`
}

type Room struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	GameType    string             `json:"game_type"`
	GameOptions []byte             `json:"game_options"`
	IsPrivate   bool               `json:"is_private"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
