// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Room struct {
	ID        pgtype.UUID
	Name      string
	GameType  string
	IsPrivate bool
	CreatedAt pgtype.Timestamp
}
