name: Deploy Go Backend (ARM) to Hetzner VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # - name: Run Go Tests
      #   run: go test ./...

      - name: Build Go application for Linux ARM64
        env:
          GOOS: linux
          GOARCH: arm64
        run: |
          echo "Building for $GOOS/$GOARCH..."
          go build -v -o ${{ secrets.BINARY_NAME }} ./backend/cmd/server/main

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Connecting to ${{ secrets.VPS_HOST }} as ${{ secrets.VPS_USER }}..."

            TARGET_PATH="${{ secrets.VPS_DEPLOY_PATH }}/${{ secrets.BINARY_NAME }}"
            echo "Target path on VPS: ${TARGET_PATH}"

            ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p ${{ secrets.VPS_DEPLOY_PATH }}"

            echo "Copying binary..."
            scp -o StrictHostKeyChecking=no ./${{ secrets.BINARY_NAME }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${TARGET_PATH}

            echo "Restarting service (${{ secrets.SERVICE_NAME }})..."
            ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "sudo systemctl restart ${{ secrets.SERVICE_NAME }}"

            echo "Deployment successful!"


