name: Deploy Go Backend (ARM) to Hetzner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.8"

      - name: Build Go application for Linux ARM64
        working-directory: ./backend
        env:
          GOOS: linux
          GOARCH: arm64
        run: |
          echo "Current directory: ${PWD}"

          echo "Listing parent directory (repo root) BEFORE build:"
          ls -la ..

          echo "Building for $GOOS/$GOARCH..."
          go build -v ./cmd/server/
          BUILD_EXIT_CODE=$?

          echo "go build command finished with exit code: ${BUILD_EXIT_CODE}"

          echo "Listing current directory (${PWD}) AFTER build:"
          ls -la .

          echo "Listing parent directory (repo root) AFTER build:"
          ls -la ..
          echo "--- End Build Step Debug ---"

          if [ ${BUILD_EXIT_CODE} -ne 0 ]; then
            echo "Go build failed!"
            exit ${BUILD_EXIT_CODE}
          fi

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Deploy Files, Run Migrations, and Restart Service
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_DEPLOY_PATH: ${{ secrets.VPS_DEPLOY_PATH }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
        run: |
          MIGRATIONS_LOCAL_PATH="./backend/db/migrate"

          # Define paths on the VPS
          DEPLOY_PATH="${VPS_DEPLOY_PATH}"
          BINARY_VPS_PATH="${DEPLOY_PATH}/server"
          MIGRATIONS_DIR_NAME="migrations"
          MIGRATIONS_VPS_PATH="${DEPLOY_PATH}/${MIGRATIONS_DIR_NAME}"
          VPS_TARGET="${VPS_USER}@${VPS_HOST}"
          MIGRATE_CMD="/usr/local/bin/migrate"

          echo "Ensuring remote directories exist..."
          ssh -o StrictHostKeyChecking=no ${VPS_TARGET} "mkdir -p ${DEPLOY_PATH} && mkdir -p ${MIGRATIONS_VPS_PATH}"

          echo "Listing files in current directory (${PWD}):"
          ls -la

          echo "Copying binary to ${BINARY_VPS_PATH}..."
          # Check if the specific binary file exists before attempting scp

          scp -o StrictHostKeyChecking=no ./server ${VPS_TARGET}:${BINARY_VPS_PATH}

          echo "Copying migrations from ${MIGRATIONS_LOCAL_PATH} to ${MIGRATIONS_VPS_PATH}..."
          scp -r -o StrictHostKeyChecking=no ${MIGRATIONS_LOCAL_PATH}/* ${VPS_TARGET}:${MIGRATIONS_VPS_PATH}/

          echo "Running commands remotely on ${VPS_TARGET}..."
          ssh -o StrictHostKeyChecking=no ${VPS_TARGET} "
            echo 'Running database migrations...'
            # Export the DATABASE_URL for the migrate command
            export DATABASE_URL='${DATABASE_URL}'
            if [ -z \"\$DATABASE_URL\" ]; then
              echo 'Error: DATABASE_URL secret is not set or empty!'
              exit 1
            fi
            echo \"Using migration path: ${MIGRATIONS_VPS_PATH}\"
            ${MIGRATE_CMD} -database \"\$DATABASE_URL\" -path ${MIGRATIONS_VPS_PATH} up
            if [ \$? -ne 0 ]; then
              echo 'Error: Database migration failed!'
              exit 1
            fi

            echo 'Restarting service (${SERVICE_NAME})...'
            sudo systemctl restart ${SERVICE_NAME}
            if [ \$? -ne 0 ]; then
              echo 'Error: Failed to restart service ${SERVICE_NAME}!'
              exit 1
            fi

            echo 'Deployment successful!'
          "
